apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: chatbot
  name: chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: chatbot
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: chatbot
    spec:
      containers:
        - args:
            - /bin/bash
            - -c
            - sleep 15 && gunicorn rest_api.application:app -b 0.0.0.0 -k uvicorn.workers.UvicornWorker --workers 1 --timeout 3000
          env:
            - name: DOCUMENTSTORE_PARAMS_HOST
              value: elasticsearch
          # image: deepset/haystack-cpu:latest
          image: localhost:5000/myimage
          name: chatbot
          ports:
            - containerPort: 8000
          resources: {}
          volumeMounts:
          # - mountPath: /home/user/rest_api
          #   name: code
          - mountPath: /app/rest_api/atq_model
            name: atq-model
          - name: config
            mountPath: "/config"
            readOnly: true
      volumes:
      # - name: code
      #   persistentVolumeClaim:
      #     claimName: pvc-haystack-rest
      - name: atq-model
        hostPath:
          path: /test_folder/atq_model
      - name: config
        configMap:
          # Provide the name of the ConfigMap you want to mount.
          name: action-cm
          # An array of keys from the ConfigMap to create as files
          items:
          - key: "chatbot.properties"
            path: "chatbot.properties"
status: {}
