apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: ui
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ui
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: ui
    spec:
      containers:
        - env:
            - name: API_ENDPOINT
              value: http://haystack-api:8000
            - name: EVAL_FILE
              value: eval_labels_example.csv
          image: deepset/haystack-streamlit-ui:latest
          name: ui
          ports:
            - containerPort: 8501
          resources: {}
      restartPolicy: Always
status: {}
