apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongo-primary
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/test_folder/mongo/mongo-primary"
    # path: "/test_folder/mongo/mongo-primary-2"

--- 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mongo-primary
spec:
  volumeName: pv-mongo-primary
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

# ---

# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pv-mongo-secondary
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteMany
#   hostPath:
#     path: "/test_folder/mongo/mongo-secondary"
#     # path: "/test_folder/mongo/mongo-secondary-2"

# --- 

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: pvc-mongo-secondary
# spec:
#   volumeName: pv-mongo-secondary
#   storageClassName: manual
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 10Gi

