#! /usr/bin/env python3
import logging
from haystack.reader.farm import FARMReader

logging.info("Training model on given data....")
reader = FARMReader(model_name_or_path='deepset/roberta-base-squad2') 
reader.train(data_dir=".", train_filename="answers.json", use_gpu=True, n_epochs=1, save_dir="my_model")
reader.save(directory="my_model")
logging.info("Training completed.......")
